CREATE TABLE IF NOT EXISTS t1_position
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code      VARCHAR(50)                              NOT NULL,
    name      VARCHAR(100)                             NOT NULL,
    is_delete INTEGER                                  NOT NULL,
    CONSTRAINT pk_t1_position PRIMARY KEY (id)
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.check_constraints
        WHERE constraint_name = 'chk_position_is_delete'
    ) THEN
        ALTER TABLE t1_position
            ADD CONSTRAINT chk_position_is_delete CHECK (t1_position.is_delete IN (0, 1));
    END IF;
END $$;