CREATE TABLE t2_employee
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(100)                             NOT NULL,
    birth_date  date                                     NOT NULL,
    position_id INTEGER                                  NOT NULL,
    id_number   INTEGER                                  NOT NULL,
    gender      INTEGER                                  NOT NULL,
    is_delete   INTEGER                                  NOT NULL,
    CONSTRAINT pk_t2_employee PRIMARY KEY (id)
);

ALTER TABLE t2_employee
    ADD CONSTRAINT FK_T2_EMPLOYEE_ON_POSITION FOREIGN KEY (position_id) REFERENCES t1_position (id);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.check_constraints
        WHERE constraint_name = 'chk_employee_is_delete'
    ) THEN
        ALTER TABLE t2_employee
            ADD CONSTRAINT chk_employee_is_delete CHECK (t2_employee.is_delete IN (0, 1));
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.check_constraints
        WHERE constraint_name = 'chk_employee_gender'
    ) THEN
        ALTER TABLE t2_employee
            ADD CONSTRAINT chk_employee_gender CHECK (t2_employee.gender IN (1, 2));
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.check_constraints
        WHERE constraint_name = 'uc_t2_employee_id_number'
    ) THEN
        ALTER TABLE t2_employee
            ADD CONSTRAINT uc_t2_employee_id_number UNIQUE (id_number);
    END IF;
END $$;
